import type { Locale } from './types';

export const QUOTES: Record<Locale, string[]> = {
  'zh-CN': [
    '千里之行，始于足下。',
    '不积跬步，无以至千里。',
    '今日事，今日毕。',
    '自律给我自由。',
    '先完成，再完美。',
    '每一个不曾起舞的日子，都是对生命的辜负。',
    '种一棵树最好的时间是十年前，其次是现在。',
    '行动是治愈恐惧的良药。',
    '把每一天都当作重新开始的机会。',
    '日拱一卒，功不唐捐。',
    '路虽远，行则将至；事虽难，做则必成。',
    '慢慢来，比较快。',
    '你的未来藏在现在的努力里。',
    '时间花在哪里，收获就在哪里。',
  ],
  en: [
    'The journey of a thousand miles begins with a single step.',
    'Small steps every day lead to big results.',
    'Do today what matters most.',
    'Discipline is the bridge between goals and accomplishment.',
    'Done is better than perfect.',
    'The best time to plant a tree was 20 years ago. The second best time is now.',
    'Action is the antidote to fear.',
    'Every day is a fresh start.',
    'Consistency compounds.',
    'The secret of getting ahead is getting started.',
    'Slow is smooth, smooth is fast.',
    'Your future is created by what you do today.',
    'Focus on progress, not perfection.',
    'Don\'t watch the clock; do what it does. Keep going.',
  ],
  ja: [
    '千里の道も一歩から。',
    '塵も積もれば山となる。',
    '今日できることは今日やる。',
    '自律こそが自由をもたらす。',
    '完璧より完成。',
    '木を植えるのに一番良い時期は20年前、次に良いのは今。',
    '行動は恐れの特効薬。',
    '毎日が新たなスタート。',
    '継続は力なり。',
    '先延ばしにせず、今始めよう。',
    '急がば回れ。',
    '未来は今日の努力の中にある。',
    '完璧ではなく、前進を目指そう。',
    '小さな一歩が大きな成果を生む。',
  ],
};
